name: Build & Analyze

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Analyze
    runs-on: macos-latest # Use ubuntu-latest if only Android is needed

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for better analysis

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3" # or your required Flutter version

      # 3. Install dependencies
      - run: flutter pub get

      # 4. Run analyzer (save output to file)
      - run: flutter analyze > flutter_analyze.txt || true

      # 5. Install Reviewdog
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # 6. Report analyzer issues with Reviewdog
      - name: Run reviewdog on flutter analyze
        run: |
          cat flutter_analyze.txt | reviewdog \
            -efm="%f:%l:%c • %m" \
            -name="flutter-analyze" \
            -reporter=github-pr-review \
            -filter-mode=file \
            -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Run tests + generate coverage
      - run: flutter test --coverage

      # 8. Run SonarQube/SonarCloud scan
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 9. Enforce quality gate (❌ fail build if gate = red)
      - uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
